name: CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Ci
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v29
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v8

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v4

    - run: |
        echo "BASE: ${{ env.NX_BASE }}"
        echo "HEAD: ${{ env.NX_HEAD }}"

    - run: nix develop --command bun install
    - run: "nix develop --command bun nx affected -t lint build"
    #
    # - run: "nix develop --command bun nx affected -t deploy"
    #   if: github.ref_name == 'main'
    #   env:
    #     FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
